version: '1.0'
services:
  db:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: e9w86036f78sd9
    volumes:
    - "./database:/var/lib/mysql"
    ports:
      - "4307:3306"
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: e9w86036f78sd9
      PMA_PORT: 4307
  mail:
    image: mailhog/mailhog:latest
    ports:
    - 8081:8025
  www:
    depends_on:
    - db
    - mail
    image: php8dev
    volumes:
    - "./www:/var/www/html"
    ports:
    - 8080:80